export class GoLogin {
    constructor(options?: {});
    browserLang: string;
    access_token: any;
    profile_id: any;
    password: any;
    extra_params: any;
    executablePath: any;
    vnc_port: any;
    fontsMasking: boolean;
    is_active: boolean;
    is_stopping: boolean;
    differentOs: boolean;
    profileOs: string;
    waitWebsocket: any;
    isEmptyFonts: boolean;
    isFirstSession: boolean;
    isCloudHeadless: any;
    storageGatewayUrl: string;
    tmpdir: any;
    autoUpdateBrowser: boolean;
    checkBrowserUpdate: any;
    browserChecker: BrowserChecker;
    uploadCookiesToServer: any;
    writeCookiesFromServer: any;
    remote_debugging_port: any;
    timezone: any;
    extensionPathsToInstall: any[];
    customArgs: any;
    restoreLastSession: any;
    processSpawned: any;
    processKillTimeout: number;
    profile_zip_path: any;
    bookmarksFilePath: any;
    checkBrowser(): Promise<any>;
    setProfileId(profile_id: any): Promise<void>;
    cookiesFilePath: any;
    getToken(username: any, password: any): Promise<void>;
    getNewFingerPrint(os: any): Promise<any>;
    profiles(): Promise<any>;
    getProfile(profile_id: any): Promise<any>;
    emptyProfile(): Promise<any>;
    getProfileS3(): Promise<any>;
    postFile(fileName: any, fileBuff: any): Promise<void>;
    emptyProfileFolder(): Promise<any>;
    convertPreferences(preferences: any): any;
    createBrowserExtension(): Promise<void>;
    extractProfile(path: any, zipfile: any): any;
    downloadProfileAndExtract(profile: any, local: any): Promise<void>;
    createZeroProfile(createCookiesTableQuery: any): Promise<void>;
    createStartup(local?: boolean): Promise<any>;
    language: any;
    resolution: {
        width: number;
        height: number;
    };
    proxy: any;
    commitProfile(): Promise<void>;
    profilePath(): any;
    orbitaExtensionPath(): any;
    getRandomInt(min: any, max: any): any;
    checkPortAvailable(port: any): Promise<boolean>;
    getRandomPort(): Promise<any>;
    getTimeZone(proxy: any): Promise<any>;
    _tz: any;
    getTimezoneWithSocks(params: any): Promise<any>;
    spawnArguments(): Promise<string[]>;
    spawnBrowser(): Promise<any>;
    port: any;
    createStartupAndSpawnBrowser(): Promise<any>;
    clearProfileFiles(): Promise<void>;
    stopAndCommit(options: any, local?: boolean): Promise<boolean>;
    uploadProfileDataToServer(): Promise<any>;
    stopBrowser(): Promise<void>;
    killBrowser(): void;
    killAndCommit(options: any, local?: boolean): Promise<void>;
    sanitizeProfile(): Promise<void>;
    getProfileDataToUpdate(): Promise<any>;
    profileExists(): Promise<boolean>;
    getRandomFingerprint(options: any): Promise<any>;
    create(options: any): Promise<any>;
    createCustom(options: any): Promise<any>;
    quickCreateProfile(name?: string): Promise<any>;
    delete(pid: any): Promise<void>;
    update(options: any): Promise<any>;
    setActive(is_active: any): void;
    getGeolocationParams(profileGeolocationParams: any, tzGeolocationParams: any): {
        mode: any;
        latitude: any;
        longitude: any;
        accuracy: any;
    };
    getViewPort(): {
        width: number;
        height: number;
    };
    postCookies(profileId: any, cookies: any): Promise<any>;
    getCookies(profileId: any): Promise<any>;
    getCookiePath(defaultFilePath: any): {
        primary: any;
        secondary: any;
    };
    writeCookiesToFile(cookies: any): Promise<void>;
    uploadProfileCookiesToServer(): Promise<any>;
    saveBookmarksToDb(): Promise<void>;
    start(): Promise<{
        status: string;
        wsUrl: any;
    }>;
    startLocal(): Promise<{
        status: string;
        wsUrl: any;
    }>;
    stop(): Promise<void>;
    stopLocal(options: any): Promise<void>;
    waitDebuggingUrl(delay_ms: any, try_count: number, remoteOrbitaUrl: any): any;
    stopRemote(): Promise<any>;
    getAvailableFonts(): string[];
    changeProfileResolution(resolution: any): Promise<any>;
    changeProfileUserAgent(userAgent: any): Promise<any>;
    changeProfileProxy(proxyData: any): Promise<any>;
}
export default GoLogin;
import BrowserChecker from "./browser/browser-checker.js";
export { exitAll, GologinApi } from "./gologin-api.js";
